name: increment-version
on: push
jobs:
  increment-version:
     name: increment-version
     runs-on: macos-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
         
       - name: Get Version
         run: THING=$(cat docs/index.html | pcregrep -o1 '\?v=([0-9]+)')
       
       - name: Increment Version
         run: THING=$((THING + 1))
       
       - name: Save Version
         run: sed "s/\?v=1/?v=${THING}/g" docs/index.html
       
       - name: switching from HTTPS to SSH
         run: git remote set-url origin ${{ secrets.ssh }}
         
       - name: check for changes
         run: git status
         
       - name: stage changed files
         run: git add .
         
       - name: commit changed files
         run: git commit -m "Incremented Version To ${THING}"
         
       - name: fetch from master
         run: git fetch origin master
         
       - name: push code to master
         run: git push origin HEAD:master
         
